### ISSUE TITLE
Introduce Version Numbers

### ISSUE THREAD

**Issue by serverhorror** [nignatiadis/IHW#3]
Hello,

could you please tag the releases. Preferrably synced to the releases on Bioconductor.

It is also very hard to package this for distribution if there is no version number to rely on.

Thanks,

**Comment by nignatiadis** [comment]
Hi,

I am not quite sure what the issue is (the description file always contains the version for R packages).

I also added a tag which points to the initial release 1.0.0 on the release branch of Bioc (v 3.3). If it helps you, I can be more diligent in the future about adding git tags. 

However, should you not be using the Bioconductor mirrors (https://github.com/Bioconductor-mirror/IHW and (https://www.bioconductor.org/packages/3.3/bioc/html/IHW.html) for packaging? I push the "stable" versions there, while things on this repository can be experimental (even on the master branch occasionally).

Let me know if I misunderstood your request.

Best,
Nikos

**Comment by serverhorror** [comment]
Hi,

I was referring to the github tag. That allows (if in sync with releases on Bioconductor, ...) to rebuild the very same package from this tag.

Thanks for adding that.
